# Alertmanager configuration for EdgeBot
global:
  # Global SMTP settings for email notifications
  # These are configured via environment variables
  smtp_smarthost: '${ALERT_SMTP_HOST}:${ALERT_SMTP_PORT}'
  smtp_from: '${ALERT_EMAIL_FROM}'
  smtp_auth_username: '${ALERT_SMTP_USER}'
  smtp_auth_password: '${ALERT_SMTP_PASS}'
  smtp_require_tls: true
  resolve_timeout: 5m

# Templates for notifications
templates:
  - '/etc/alertmanager/*.tmpl'

# Route tree for determining where alerts should be sent
route:
  # Root route - all alerts pass through here
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'null'  # Default receiver (does nothing)
  
  routes:
    # Email route for alerts with severity >= warning (if email is configured)
    - match_re:
        severity: (critical|warning)
      receiver: 'email-alerts'
      group_wait: 10s
      repeat_interval: 1h
    
    # Critical alerts - could be routed to PagerDuty, immediate notifications, etc.
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 30m
    
    # Warning alerts - could be routed to Slack, email, etc.  
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 4h

# Inhibition rules - suppress certain alerts when others are firing
inhibit_rules:
  # Suppress sink alerts when mothership is down
  - source_match:
      alertname: 'MothershipDown'
    target_match_re:
      alertname: '.*Writes.*'
    equal: ['job']
  
  # Suppress latency alerts when there are no events being processed
  - source_match:
      alertname: 'NoIngestEvents'
    target_match_re:
      alertname: 'High.*Latency.*'
    equal: ['job']

# Receivers define how to send notifications
receivers:
  # Null receiver - discards alerts (default for demo/development)
  - name: 'null'

  # Email receiver for all critical and warning alerts
  - name: 'email-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_TO}'

  # Critical alerts receiver
  - name: 'critical-alerts'
    # Uncomment and configure for Slack notifications:
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'
    #     channel: '#alerts-critical'
    #     title: 'Critical Alert: {{ .GroupLabels.alertname }}'
    #     text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    #     send_resolved: true
    
    # Email configuration for critical alerts (high priority)
    email_configs:
      - to: '${ALERT_EMAIL_TO}'

  # Warning alerts receiver  
  - name: 'warning-alerts'
    # Uncomment and configure for Slack notifications:
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'
    #     channel: '#alerts-warnings'
    #     title: 'Warning: {{ .GroupLabels.alertname }}'
    #     text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    #     send_resolved: true

# Configuration notes:
# 
# To enable email notifications:
# 1. Create a .env file in the root directory with your SMTP settings:
#    ALERT_SMTP_HOST=smtp.gmail.com
#    ALERT_SMTP_PORT=587
#    ALERT_SMTP_USER=your-email@gmail.com
#    ALERT_SMTP_PASS=your-app-password
#    ALERT_SMTP_STARTTLS=true
#    ALERT_EMAIL_FROM=alertmanager@yourcompany.com
#    ALERT_EMAIL_TO=ops-team@yourcompany.com
# 2. Start the observability stack: docker compose -f compose.observability.yml up -d
# 3. Verify configuration at: http://localhost:9093/#/status
# 
# To enable Slack notifications:
# 1. Create a Slack webhook: https://api.slack.com/messaging/webhooks
# 2. Replace 'YOUR_SLACK_WEBHOOK_URL_HERE' with your webhook URL
# 3. Uncomment the slack_configs sections above
# 4. Restart Alertmanager: docker compose restart alertmanager
#
# For PagerDuty, OpsGenie, and other integrations, see:
# https://prometheus.io/docs/alerting/latest/configuration/