version: '3.8'

services:
  central:
    build:
      context: ./central_platform
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./central_platform/data:/app/data
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  edge:
    build:
      context: ./edge_node
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - EDGE_ID=edge-1
      - CENTRAL_API_BASE=http://central:8000
      - SEND_INTERVAL_SEC=5
      - PYTHONPATH=/app
    depends_on:
      central:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  default:
    name: edgebot-network