# EdgeBot configuration (example)
# Copy to config.yaml to use. Defaults are safe for a local file-based deployment.

server:
  host: 0.0.0.0
  port: 8080

observability:
  health_port: 8081
  metrics_port: 8081
  log_level: info

inputs:
  syslog:
    enabled: true
    udp_port: 5514
    tcp_port: 5515
  snmp:
    enabled: false
    targets: []
  weather:
    enabled: false

output:
  mothership:
    # For simple deployments we write payloads to disk inside the data volume:
    url: "file:///var/lib/edgebot/out"
    batch_size: 100
    batch_timeout: 5
    compression: true
    # To send to HTTPS, set:
    # url: "https://your-server/ingest"
    # auth_token: "your-token"
    # tls_verify: true

security:
  run_as_non_root: true