version: "3.8"

services:
  edgebot:
    container_name: edgebot
    build:
      context: .
      dockerfile: Dockerfile
    image: edgebot:local
    restart: always
    env_file:
      - ./.env
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "5514:5514/udp"
      - "5515:5515"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data/logs:/var/log/edgebot
      - ./data:/var/lib/edgebot
      - ./data/out:/var/lib/edgebot/out
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s