apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mothership.fullname" . }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mothership.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        # Force pod restart when config changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "mothership.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mothership.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            # Core configuration
            - name: MOTHERSHIP_DB_DSN
              value: {{ include "mothership.databaseDsn" . | quote }}
            - name: MOTHERSHIP_LOG_LEVEL
              value: {{ .Values.config.logging.level | quote }}
            
            # Database configuration
            - name: TSDB_ENABLED
              value: {{ .Values.config.database.enabled | quote }}
            
            # Loki configuration
            - name: LOKI_ENABLED
              value: {{ .Values.config.loki.enabled | quote }}
            {{- if .Values.config.loki.enabled }}
            - name: LOKI_URL
              value: {{ include "mothership.lokiUrl" . | quote }}
            {{- if .Values.config.loki.tenantId }}
            - name: LOKI_TENANT_ID
              value: {{ .Values.config.loki.tenantId | quote }}
            {{- end }}
            {{- if .Values.config.loki.username }}
            - name: LOKI_USERNAME
              value: {{ .Values.config.loki.username | quote }}
            {{- end }}
            {{- if .Values.config.loki.password }}
            - name: LOKI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mothership.fullname" . }}-loki
                  key: password
            {{- end }}
            - name: LOKI_BATCH_SIZE
              value: {{ .Values.config.loki.batchSize | quote }}
            - name: LOKI_BATCH_TIMEOUT_SECONDS
              value: {{ .Values.config.loki.batchTimeoutSeconds | quote }}
            {{- end }}
            
            # LLM configuration
            - name: MOTHERSHIP_LLM_ENABLED
              value: {{ .Values.config.llm.enabled | quote }}
            {{- if .Values.config.llm.enabled }}
            - name: MOTHERSHIP_LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mothership.fullname" . }}-llm
                  key: api-key
            {{- end }}
            
            # Additional environment variables
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            successThreshold: {{ .Values.probes.liveness.successThreshold }}
          {{- end }}
          
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
          {{- end }}
          
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            successThreshold: {{ .Values.probes.startup.successThreshold }}
          {{- end }}
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /app/data
            {{- end }}
      
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mothership.fullname" . }}-data
        {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}