apiVersion: v2
name: observability
description: EdgeBot Observability Stack - Prometheus, Loki, Grafana, and Alertmanager
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/iLodeStar/AIOps-EdgeBot-poc
sources:
  - https://github.com/iLodeStar/AIOps-EdgeBot-poc
maintainers:
  - name: EdgeBot Team
keywords:
  - observability
  - prometheus
  - grafana
  - loki
  - alertmanager
  - monitoring
dependencies:
  - name: kube-prometheus-stack
    version: "~65.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    alias: prometheus-stack
  - name: loki
    version: "~6.0.0"
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: grafana
    version: "~8.0.0"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.standalone
annotations:
  category: Observability