name: Build EdgeBot binary

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build (Linux x86_64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install -r edge_node/requirements.txt pyinstaller

      - name: Build binary
        run: |
          bash scripts/build_binary.sh
          ls -lah edge_node/dist || true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: edgebot-linux-x86_64
          path: edge_node/dist/edgebot
          if-no-files-found: error
          retention-days: 7

  release:
    name: Publish Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: edgebot-linux-x86_64
          path: dist

      - name: Generate checksum
        run: |
          cd dist
          sha256sum edgebot > edgebot.sha256
          ls -lah

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/edgebot
            dist/edgebot.sha256