name: Lint Helm Charts

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'charts/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'charts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.1'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Add Helm repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add timescale https://charts.timescale.com/
          helm repo update

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Update chart dependencies
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          for chart in charts/*/; do
            if [[ -f "$chart/Chart.yaml" ]] && [[ -f "$chart/requirements.yaml" || $(grep -q "dependencies:" "$chart/Chart.yaml") ]]; then
              echo "Updating dependencies for $chart"
              helm dependency update "$chart"
            fi
          done

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          if ! ct lint --target-branch ${{ github.event.repository.default_branch }} --config .github/ct.yaml; then
            echo "Chart-testing failed, falling back to basic helm lint..."
            failed=false
            for chart in charts/*/; do
              if [[ -f "$chart/Chart.yaml" ]]; then
                echo "Linting $chart with helm lint..."
                if ! helm lint "$chart"; then
                  echo "ERROR: helm lint failed for $chart"
                  failed=true
                fi
              fi
            done
            if [[ "$failed" == "true" ]]; then
              exit 1
            fi
            echo "Basic helm linting completed successfully"
          fi

      - name: Install kubeconform
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
          sudo mv kubeconform /usr/local/bin

      - name: Validate Kubernetes manifests with kubeconform
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          for chart in charts/*/; do
            if [[ -f "$chart/Chart.yaml" ]]; then
              echo "Validating $chart"
              # Check if chart has dependencies and update them
              if [[ -f "$chart/requirements.yaml" ]] || grep -q "dependencies:" "$chart/Chart.yaml"; then
                echo "Updating dependencies for $chart"
                helm dependency update "$chart" || {
                  echo "Warning: Failed to update dependencies for $chart, skipping kubeconform validation"
                  continue
                }
              fi
              # Template the chart and validate
              echo "Templating and validating $chart..."
              if ! helm template test-release "$chart" | kubeconform -strict -summary -verbose; then
                echo "Error: kubeconform validation failed for $chart"
                exit 1
              fi
            fi
          done

  # Optional: smoke test with kind
  smoke-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.1'

      - name: Set up kind
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: helm-test
          kubectl_version: v1.27.0

      - name: Add Helm repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add timescale https://charts.timescale.com/
          helm repo update

      - name: Install Prometheus Operator CRDs
        run: |
          kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
          kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
          kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
          kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
          kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml

      - name: Test mothership chart
        run: |
          helm install test-mothership ./charts/mothership \
            --set image.repository=nginx \
            --set image.tag=alpine \
            --set config.database.enabled=false \
            --set config.loki.enabled=false \
            --dry-run --debug

      - name: Test observability chart (template only - no deployment due to complexity)
        run: |
          helm dependency update ./charts/observability
          helm template test-observability ./charts/observability \
            --set prometheus-stack.prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage=1Gi \
            --set prometheus-stack.grafana.persistence.size=1Gi